version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mong'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017-27019:27017-27019'
